


d := Day17 new.
d range: ( d puzzleInput1 ) .

Transcript clear.
m := Day17Morph new openInWorld.
m plotWalls: d .   
m solve.

" =================================== " 

m := Day17Morph new openInWorld.
m puzzleExample1. 
Transcript clear.


Gofer new
  renggli: 'petit';
  package: 'PetitParser';
  package: 'PetitTests';
  load.



Point

(0@0) className. 
(0@0) - (2@3).  -2@ -3


--------------------
